services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          memory: 512m

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

volumes:
  redis_data:
